# Generated by Django 5.1.5 on 2025-02-12 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_state_alter_task_image_kanban'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kanban',
            options={'verbose_name': 'Канбан', 'verbose_name_plural': 'Канбаны'},
        ),
        migrations.AlterModelOptions(
            name='task',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RemoveField(
            model_name='task',
            name='state',
        ),
        migrations.AddField(
            model_name='task',
            name='kanban',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='tasks.kanban'),
            preserve_default=False,
        ),
    ]
