# Generated by Django 5.1.5 on 2025-02-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_kanban_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='state',
            field=models.CharField(choices=[('PLANNED', 'PLANNED'), ('IN_PROGRESS', 'IN_PROGRESS'), ('REVIEW', 'REVIEW'), ('DONE', 'DONE'), ('OVERDUE', 'OVERDUE')], default='PLANNED', max_length=100),
        ),
    ]
