# Generated by Django 5.1.5 on 2025-02-22 09:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='datetime_assigned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='datetime_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 22, 9, 54, 55, 370825, tzinfo=datetime.timezone.utc), editable=False),
        ),
        migrations.AddField(
            model_name='task',
            name='datetime_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='datetime_done',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='datetime_review',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
