# Generated by Django 5.1.5 on 2025-02-22 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_task_datetime_assigned_task_datetime_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='datetime_created',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
    ]
