# Generated by Django 5.1.5 on 2025-02-28 22:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_alter_task_datetime_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='datetime_last_update',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
