# Generated by Django 5.1.5 on 2025-03-07 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_alter_task_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanban',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
