# Generated by Django 5.1.5 on 2025-03-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kanban',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
